#!/bin/bash

# Move categorized images to their respective folders

# Restaurant Interiors
mv "images/about-restaurant.jpg" "images/restaurant-interiors/"
mv "images/bar-area.jpg" "images/restaurant-interiors/"
mv "images/bar-counter.jpg" "images/restaurant-interiors/"
mv "images/bistro-seating-area.jpg" "images/restaurant-interiors/"
mv "images/cafe-atmosphere.jpg" "images/restaurant-interiors/"
mv "images/cafe-brunch-table.jpg" "images/restaurant-interiors/"
mv "images/cafe-interior-casual.jpg" "images/restaurant-interiors/"
mv "images/cafe-interior-plants.jpg" "images/restaurant-interiors/"
mv "images/candlelit-dining.jpg" "images/restaurant-interiors/"
mv "images/casual-restaurant.jpg" "images/restaurant-interiors/"
mv "images/coffee-cafe-interior.jpg" "images/restaurant-interiors/"
mv "images/coffee-shop-interior.jpg" "images/restaurant-interiors/"
mv "images/cozy-bar-atmosphere.jpg" "images/restaurant-interiors/"
mv "images/cozy-cafe-interior.jpg" "images/restaurant-interiors/"
mv "images/cozy-cafe.jpg" "images/restaurant-interiors/"
mv "images/cozy-coffee-shop-interior.jpg" "images/restaurant-interiors/"
mv "images/cozy-dining-room.jpg" "images/restaurant-interiors/"
mv "images/cozy-restaurant-dining.jpg" "images/restaurant-interiors/"
mv "images/cozy-restaurant-interior.jpg" "images/restaurant-interiors/"
mv "images/cozy-restaurant-lighting.jpg" "images/restaurant-interiors/"
mv "images/elegant-dining-room.jpg" "images/restaurant-interiors/"
mv "images/elegant-dining.jpg" "images/restaurant-interiors/"
mv "images/elegant-restaurant-interior.jpg" "images/restaurant-interiors/"
mv "images/elegant-restaurant.jpg" "images/restaurant-interiors/"
mv "images/farmhouse-dining.jpg" "images/restaurant-interiors/"
mv "images/fine-dining-interior.jpg" "images/restaurant-interiors/"
mv "images/industrial-chic.jpg" "images/restaurant-interiors/"
mv "images/luxury-restaurant-interior.jpg" "images/restaurant-interiors/"
mv "images/modern-cafe-interior.jpg" "images/restaurant-interiors/"
mv "images/modern-dining-room.jpg" "images/restaurant-interiors/"
mv "images/modern-restaurant-bar.jpg" "images/restaurant-interiors/"
mv "images/modern-restaurant-dining.jpg" "images/restaurant-interiors/"
mv "images/modern-restaurant-interior-lighting.jpg" "images/restaurant-interiors/"
mv "images/modern-restaurant-interior.jpg" "images/restaurant-interiors/"
mv "images/restaurant-interior-2.jpg" "images/restaurant-interiors/"
mv "images/restaurant-interior-fine-dining.jpg" "images/restaurant-interiors/"
mv "images/restaurant-interior_1.jpg" "images/restaurant-interiors/"
mv "images/romantic-lighting.jpg" "images/restaurant-interiors/"
mv "images/rustic-dining-room.jpg" "images/restaurant-interiors/"
mv "images/rustic-interior.jpg" "images/restaurant-interiors/"
mv "images/upscale-restaurant-interior.jpg" "images/restaurant-interiors/"
mv "images/warm-restaurant-lighting.jpg" "images/restaurant-interiors/"

echo "Moved restaurant interior images"

# Food dishes (split into smaller batches)
mv "images/artisan-bread-bakery.jpg" "images/food-dishes/"
mv "images/artisan-bread-plate.jpg" "images/food-dishes/"
mv "images/artisan-pizza-fresh.jpg" "images/food-dishes/"
mv "images/artisan-pizza.jpg" "images/food-dishes/"
mv "images/asian-ramen-bowl.jpg" "images/food-dishes/"
mv "images/asian-sushi-platter.jpg" "images/food-dishes/"
mv "images/avocado-egg-toast-unsplash.jpg" "images/food-dishes/"
mv "images/bread-basket-artisan.jpg" "images/food-dishes/"
mv "images/bread-basket-table.jpg" "images/food-dishes/"
mv "images/bread-basket.jpg" "images/food-dishes/"

echo "Moved first batch of food images"